services:
  app:
    build: ../app
    container_name: app
    env_file: ../.env
    depends_on:
      - pg

  pg:
    image: postgres:16-alpine
    container_name: pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../data-lake:/data-lake:ro
      - ../etl:/etl:ro
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  pgdata:
