name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./app
          tags: ${{ vars.DOCKERHUB_USERNAME }}/movieflix-analytics:temp
          push: false
          load: true

      - name: Smoke test (ephemeral)
        run: |
          docker run -d --rm -p 3000:3000 --name app ${{ vars.DOCKERHUB_USERNAME }}/movieflix-analytics:temp
          sleep 3
          code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/health || true)
          docker stop app
          if [ "$code" != "200" ]; then
            echo "Healthcheck falhou: HTTP $code"
            exit 1
          fi

      - name: Build & Push (main only)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/movieflix-analytics:latest
            ${{ vars.DOCKERHUB_USERNAME }}/movieflix-analytics:${{ github.sha }}
